#mybatis的连接
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ojsystem.entity
#数据库连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ojsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  jackson:
    time-zone: GMT+8
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 767324214@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: phxalbhwlsvlbehd
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

server:
  port: 8888




