#mybatis的连接
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ojsystem.entity
#数据库连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ojsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  jackson:
    time-zone: GMT+8
server:
  port: 8888



